manifest = "833b5daec2013a8801e22cbb276369b8a2355a72215ca0e8cc413f0eb24e78b4"

[[dependency]]
package = "github.com/buckaroo-pm/boost-bind"
target = "//:bind"

[[dependency]]
package = "github.com/buckaroo-pm/boost-integer"
target = "//:integer"

[lock."github.com/buckaroo-pm/boost-bind"]
versions = [ "1.31.0" ]
revision = "4efd078966a1bf137770f29d956d505c02830c82"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.31.0" ]
revision = "a83d1fbd2e2217c49e5ed2d4274bcdb812bcc0cd"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.31.0" ]
revision = "3c57233157a56605204d3818b73dc513e29b446a"

[lock."github.com/buckaroo-pm/boost-integer"]
versions = [ "1.31.0" ]
revision = "8cde5e38f11ceb0c21d4d7f04cd906a14a39a878"

[lock."github.com/buckaroo-pm/boost-preprocessor"]
versions = [ "1.31.0" ]
revision = "5b3299ecfa2d7be9b883e02a61a84dc407884804"

[lock."github.com/buckaroo-pm/boost-static_assert"]
versions = [ "1.31.0" ]
revision = "367fcb3e762a49fb82bca262e018f9653e6f1881"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.31.0" ]
revision = "0fe40a434ee2953887b8cc8f6f2aa442d287f503"

[lock."github.com/buckaroo-pm/boost-utility"]
versions = [ "1.31.0" ]
revision = "437065637a5d6ccfcacffa5ac3c50a358f6cd311"
