manifest = "eb0cafca74bd3ef2df94bb3b708e472dc530725bba18e77667d0db14d0f330b4"

[[dependency]]
package = "github.com/buckaroo-pm/boost-integer"
target = "//:integer"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.24.0" ]
revision = "37278170bcbe6e22f6eebed0d33d5df4e0d015e1"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.24.0" ]
revision = "9bde767a62803ab4aa713772d98815bd948d9d47"

[lock."github.com/buckaroo-pm/boost-integer"]
versions = [ "1.24.0" ]
revision = "0498451b57c7d366846899c14edc51b812451e51"

[lock."github.com/buckaroo-pm/boost-static_assert"]
versions = [ "1.24.0" ]
revision = "d3cf518d3ee95fbd73eda7e8733598b93cd93d5a"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.24.0" ]
revision = "36d22132d39fc31e27c7ba1f61d91b294e12aa78"

[lock."github.com/buckaroo-pm/boost-utility"]
versions = [ "1.24.0" ]
revision = "b6e1c5e00c7f831c78fcf94273a6c170802d4ad8"
