manifest = "d971786a927d916571ca44c13540cc96d401056d07beb73870c89050df7ca0d1"

[[dependency]]
package = "github.com/buckaroo-pm/boost-bind"
target = "//:bind"

[[dependency]]
package = "github.com/buckaroo-pm/boost-integer"
target = "//:integer"

[lock."github.com/buckaroo-pm/boost-bind"]
versions = [ "1.33.0" ]
revision = "4b1c6be407ee5d2e3c2102884ce6cbe8a64f5d29"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.33.0" ]
revision = "65a8650af82725f556021c523cb3a87f6b93c268"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.33.0" ]
revision = "40ad58a6eec511d5c9b370e6316df7d27e2ed0ab"

[lock."github.com/buckaroo-pm/boost-integer"]
versions = [ "1.33.0" ]
revision = "79ac7fe07fd054fe8f01ee37010f21b4ac221ea9"

[lock."github.com/buckaroo-pm/boost-preprocessor"]
versions = [ "1.33.0" ]
revision = "13db417fd9a81f2558365e854caf8d42a9100289"

[lock."github.com/buckaroo-pm/boost-static_assert"]
versions = [ "1.33.0" ]
revision = "4acae7173fa1e199cb9bbe0d13bd447e60f5f23d"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.33.0" ]
revision = "4f62fa95b94166f6c54732ee7e93c53ea6f25e9a"

[lock."github.com/buckaroo-pm/boost-utility"]
versions = [ "1.33.0" ]
revision = "43f2eff4cf50a5fde6eaee135260bf7bd7bccb36"
