manifest = "74131baecabf334f4615c263532419c98ffd4543ec8fc84ddbfd38bdf070d7e9"

[[dependency]]
package = "github.com/buckaroo-pm/boost-bind"
target = "//:bind"

[[dependency]]
package = "github.com/buckaroo-pm/boost-integer"
target = "//:integer"

[lock."github.com/buckaroo-pm/boost-bind"]
versions = [ "1.25.1" ]
revision = "9d4dd9b4768faa66ae9f75acceb2cb31fd28f14d"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.25.1" ]
revision = "506f73de6fa609a455f618dadb53af6e3ce3ac22"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.25.1" ]
revision = "778c84d4c767d9e75714fddfb34aec8907ee0fa0"

[lock."github.com/buckaroo-pm/boost-integer"]
versions = [ "1.25.1" ]
revision = "1658243eb2c77d7321a04ba8d74d4613a0fd3ab3"

[lock."github.com/buckaroo-pm/boost-static_assert"]
versions = [ "1.25.1" ]
revision = "2c3123a6e0504ab0a303fd9cdc16837af2ef1f11"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.25.1" ]
revision = "f57224ef8f3ed8623c077e2ca32251c6f38e0471"

[lock."github.com/buckaroo-pm/boost-utility"]
versions = [ "1.25.1" ]
revision = "dff3af2e1dbaabc2baf54c1d23578e83afae75c0"
